# type: ignore
import sys
from typing import Literal, List, Any, Optional, Tuple, Dict, Callable
import numpy as np
import enum
import numpy
from .tensor import Tensor_float

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:ElementwiseMath.hpp>    ####################

#  ------------------------------------------------------------------------
#      <template specializations for function relu>
@overload
def relu(input: tensor.Tensor<float>) -> tensor.Tensor<float>:
    pass
#      </template specializations for function relu>
#  ------------------------------------------------------------------------

#  ------------------------------------------------------------------------
#      <template specializations for function tanh>
@overload
def tanh(input: tensor.Tensor<float>) -> tensor.Tensor<float>:
    pass
#      </template specializations for function tanh>
#  ------------------------------------------------------------------------

#  ------------------------------------------------------------------------
#      <template specializations for function pow>
@overload
def pow(input: tensor.Tensor<float>, exponent: float) -> tensor.Tensor<float>:
    pass
#      </template specializations for function pow>
#  ------------------------------------------------------------------------

#  ------------------------------------------------------------------------
#      <template specializations for function abs>
@overload
def abs(input: tensor.Tensor<float>) -> tensor.Tensor<float>:
    pass
#      </template specializations for function abs>
#  ------------------------------------------------------------------------

#  ------------------------------------------------------------------------
#      <template specializations for function exp>
@overload
def exp(input: tensor.Tensor<float>) -> tensor.Tensor<float>:
    pass
#      </template specializations for function exp>
#  ------------------------------------------------------------------------

#  ------------------------------------------------------------------------
#      <template specializations for function log>
@overload
def log(input: tensor.Tensor<float>) -> tensor.Tensor<float>:
    pass
#      </template specializations for function log>
#  ------------------------------------------------------------------------

#  ------------------------------------------------------------------------
#      <template specializations for function sqrt>
@overload
def sqrt(input: tensor.Tensor<float>) -> tensor.Tensor<float>:
    pass
#      </template specializations for function sqrt>
#  ------------------------------------------------------------------------

#  ------------------------------------------------------------------------
#      <template specializations for function clip>
@overload
def clip(input: tensor.Tensor<float>, min: float, max: float) -> tensor.Tensor<float>:
    pass
#      </template specializations for function clip>
#  ------------------------------------------------------------------------


####################    </generated_from:ElementwiseMath.hpp>    ####################

# </litgen_stub> // Autogenerated code end!